// lib/models/notification_preferences.dart

/// Helper class providing default values and descriptions for each
/// notification preference, used by the settings screen to build
/// the notification configuration UI dynamically.
///
/// Each preference item maps to a column in the [NotificationPreferences]
/// database table and controls whether a specific type of notification
/// is generated by the [NotificationService].
class NotificationPreferenceItem {
  final String key;
  final String title;
  final String description;
  final bool defaultValue;

  const NotificationPreferenceItem({
    required this.key,
    required this.title,
    required this.description,
    this.defaultValue = true,
  });
}

/// A static registry of all available notification preference items.
/// The settings screen iterates over this list to build toggle switches
/// for each notification category.
///
/// Categories include:
/// - Timer completion alerts
/// - Task deadline reminders (with configurable lead time)
/// - Project time limit warnings (with configurable threshold percentage)
/// - Automated weekly productivity summaries
/// - Overdue invoice payment alerts
/// - Overdue task alerts
/// - Project hour milestone celebrations
/// - Sound and vibration toggles
class NotificationPreferenceDefinitions {
  static const List<NotificationPreferenceItem> togglePreferences = [
    NotificationPreferenceItem(
      key: 'timerStopNotifications',
      title: 'Timer Completion',
      description:
          'Get notified when a timer is stopped, showing the task name and total duration tracked for the session.',
    ),
    NotificationPreferenceItem(
      key: 'deadlineReminders',
      title: 'Deadline Reminders',
      description:
          'Receive advance warnings before task deadlines arrive, giving you time to prioritize and complete work.',
    ),
    NotificationPreferenceItem(
      key: 'timeLimitWarnings',
      title: 'Time Limit Warnings',
      description:
          'Get alerted when tracked hours on a project approach or exceed the configured monthly time limit.',
    ),
    NotificationPreferenceItem(
      key: 'weeklySummary',
      title: 'Weekly Summary',
      description:
          'Receive a comprehensive weekly report of your tracked hours, earnings, completed tasks, and expenses.',
    ),
    NotificationPreferenceItem(
      key: 'invoiceOverdueAlerts',
      title: 'Invoice Overdue Alerts',
      description:
          'Get notified when invoices pass their due date without being marked as paid, so you can follow up.',
    ),
    NotificationPreferenceItem(
      key: 'taskOverdueAlerts',
      title: 'Task Overdue Alerts',
      description:
          'Receive alerts when tasks pass their deadline without being completed, helping you stay on schedule.',
    ),
    NotificationPreferenceItem(
      key: 'milestoneNotifications',
      title: 'Milestone Celebrations',
      description:
          'Get celebratory notifications when you reach significant hour milestones (10h, 25h, 50h, 100h, etc.) on projects.',
    ),
  ];

  static const List<NotificationPreferenceItem> feedbackPreferences = [
    NotificationPreferenceItem(
      key: 'soundEnabled',
      title: 'Sound',
      description: 'Play a sound when notifications are created.',
    ),
    NotificationPreferenceItem(
      key: 'vibrationEnabled',
      title: 'Vibration',
      description: 'Vibrate when notifications are created.',
    ),
  ];

  /// Maps for the numeric threshold preferences with their metadata.
  /// These require special UI treatment (sliders or number inputs) rather
  /// than simple toggle switches.
  static const Map<String, String> thresholdPreferences = {
    'deadlineReminderMinutes': 'Deadline Reminder Lead Time',
    'timeLimitWarningPercent': 'Time Limit Warning Threshold',
  };

  /// Returns a descriptive label for the deadline reminder lead time value,
  /// converting the raw minutes value into a human-readable format like
  /// "30 minutes", "1 hour", "2 hours", etc.
  static String getDeadlineReminderLabel(int minutes) {
    if (minutes < 60) {
      return '$minutes minutes before';
    } else if (minutes == 60) {
      return '1 hour before';
    } else if (minutes < 1440) {
      return '${(minutes / 60).round()} hours before';
    } else {
      return '${(minutes / 1440).round()} day(s) before';
    }
  }

  /// Returns a descriptive label for the time limit warning threshold,
  /// formatting the percentage value into a readable string.
  static String getTimeLimitLabel(int percent) {
    return 'Warn at $percent% of monthly limit';
  }
}
